# Generated by Django 4.0.5 on 2022-06-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imange',
            new_name='image',
        ),
    ]
